# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: setup-netcore
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack -p:Version="1.0.0" -p:RepositoryType="git" -p:RepositoryUrl="https://github.com/${{ github.repository }}" -c Release -o dist
      - name: Publish on NuGet
        run: dotnet nuget push "dist\*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source 'https://api.nuget.org/v3/index.json'
      - name: Publish on github packages
        run: dotnet nuget push "dist\*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
